journal/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.AboutView.as_view(), name='about'),
]

journal/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    re_path(
        r'post_delete/(?P<post_id>[0-9]+)/(?P<referer>.+)/$',
        views.post_delete,
        name='post_delete'
    ),
]

journal/journal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path("ckeditor5/", include('django_ckeditor_5.urls'),
         name="ck_editor_5_upload_file"),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

journal/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

journal/templates/includes/buttons_top_bottom.html
<a href="#" id="scroll_top" title="Наверх"></a>
<a href="#" id="scroll_bottom" title="Вниз"></a>

journal/templates/includes/footer.html
{% load static %}
<footer class="p-3 bg-dark text-white">
  <div class="container">
    <div class="text-center" >
      <img src="{% static 'img/logo/logo112.png' %}" height="24" width="24">
      © {{ year }} Copyright:
      <a class="text-white" href="{% url 'blog:index' %}">ГБУ "Система 112"</a>
    </div>
  </div>
</footer>

journal/templates/includes/header.html
{% load static %}
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-between">

      <a href="{% url 'blog:index' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img src="{% static 'img/logo/logo112.png' %}" style="width: auto; height: auto;" />
      </a>

      {% with view_name=request.resolver_match.view_name post_author=request.resolver_match.kwargs.username %}
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'blog:index' %}" class="nav-link px-2 {% if view_name  == 'blog:index' %}text-secondary{% else %}text-white{% endif %}">Главная</a></li>
        <li><a href="{% url 'blog:post_create' %}" class="nav-link px-2 {% if view_name  == 'blog:post_create' %}text-secondary{% else %}text-white{% endif %}">Написать</a></li>
        <li><a href="{% url 'blog:profile' request.user.username %}" class="nav-link px-2 {% if post_author  == request.user.username %}text-secondary{% else %}text-white{% endif %}">Мои посты</a></li>
        <li><a href="{% url 'about:about' %}" class="nav-link px-2 {% if view_name  == 'about:about' %}text-secondary{% else %}text-white{% endif %}">О сайте</a></li>
      </ul>
      
      <form id="search-form" class="d-flex col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% if view_name  == 'blog:profile' %}{% url 'blog:profile' post_author %}{% else %}{% url 'blog:index' %}{% endif %}"> 
        <input id="search-input" type="search" class="form-control form-control-dark me-2" placeholder="Найти..." value="{{ request.GET.q }}" aria-label="Search" name="q">
        {% include 'includes/exclude_get_params/exclude_get_params.html' with exclude_get_params='q' %}
        <button class="btn btn-light" type="submit">Искать</button>
      </form>
      {% endwith %}
      
      <a class="btn btn-danger" id="logoutButton" data-logout-url="{% url 'users:logout' %}">Выйти</a>

    </div>
  </div>
</header>

journal/templates/includes/logout.html
<div id="logoutModal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Вы уверены, что хотите выйти?</h5>
        <button id="exitLogout" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-footer">
        <button id="cancelLogout" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <button id="confirmLogout" type="button" class="btn btn-primary">Да</button>
      </div>
    </div>
  </div>
</div>