journal/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    re_path(
        r'post_delete/(?P<post_id>[0-9]+)/(?P<referer>.+)/$',
        views.post_delete,
        name='post_delete'
    ),
]

journal/journal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path("ckeditor5/", include('django_ckeditor_5.urls'),
         name="ck_editor_5_upload_file"),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

journal/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


User = get_user_model()


class Tag(models.Model):
    """Модель 'Теги' для постов.

    Validators:
        - Каждый тег должен быть уникальным.
        - Одиним тегом можно пометить пост только один раз.
    """
    name = models.CharField(
        max_length=255,
        verbose_name='название тега',
        unique=True,
    )
    slug = models.SlugField(
        max_length=20,
        verbose_name='слаг',
        unique=True,
    )

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'
        ordering = ['id']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'slug'],
                name='unique_post_tag',
            )
        ]

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    """Модель 'Посты'."""
    text = CKEditor5Field(
        verbose_name='текст поста',
        help_text='введите текст поста',
        config_name='extends',
    )
    pub_date = models.DateTimeField(
        verbose_name='дата публикации',
        auto_now_add=True,
    )
    edit_date = models.DateTimeField(
        verbose_name='дата редактирования',
        auto_now=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
        related_name='posts',
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='теги',
        related_name='posts',
        blank=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return str(self.pk)


class ActionLog(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='автор',
        related_name='actionlogs',
    )
    action = models.TextField(
        verbose_name='лог',
    )
    text = CKEditor5Field(
        verbose_name='текст поста',
        config_name='extends',
    )
    timestamp = models.DateTimeField(
        verbose_name='дата',
        auto_now_add=True,
    )
    post_id = models.PositiveIntegerField(
        verbose_name='id поста',
    )

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

journal/blog/forms.py
from django import forms

from .models import Post, Tag


class PostForm(forms.ModelForm):
    """Форма для создания и редактирования постов."""
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='Теги',
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].required = False
        self.fields["tags"].required = False

    class Meta:
        model = Post
        fields = ('text', 'tags',)

journal/blog/views.py
from urllib.parse import urlparse

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PostForm
from .models import Post, Tag
from .utils import (get_GET_params_for_paginator, include_paginator,
                    search_and_filter)

User = get_user_model()


@login_required
def index(request):
    posts = search_and_filter(request, Post.objects.all())
    posts_paginator = include_paginator(request, posts)
    tags = Tag.objects.all()

    return render(
        request=request,
        template_name='blog/index.html',
        context={
            'posts_paginator': posts_paginator,
            'tags': tags,
            'get_params': dict(request.GET),
            'GET_params_for_paginator': get_GET_params_for_paginator(
                request,
                ('tags', 'q')
            ),
        },
    )


@login_required
def profile(request, username):
    author = get_object_or_404(User, username=username)
    count_posts = author.posts.all().count()
    posts = author.posts.all()
    posts = search_and_filter(request, posts)
    posts_paginator = include_paginator(request, posts)
    tags = Tag.objects.all()

    return render(
        request=request,
        template_name='blog/profile.html',
        context={
            'author': author,
            'count_posts': count_posts,
            'posts_paginator': posts_paginator,
            'tags': tags,
            'get_params': dict(request.GET),
            'GET_params_for_paginator': get_GET_params_for_paginator(
                request,
                ('tags', 'q')
            ),
        }
    )


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    count_posts = author.posts.all().count()
    referer = request.META.get('HTTP_REFERER')

    return render(
        request=request,
        template_name='blog/post_detail.html',
        context={
            'count_posts': count_posts,
            'post': post,
            'referer': referer,
        }
    )


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        post.tags.clear()
        post.tags.set(form.cleaned_data['tags'])
        return redirect('blog:profile', request.user.username)
    return render(
        request=request,
        template_name='blog/create_post.html',
        context={
            'form': form
        }
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('blog:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        post.tags.clear()
        post.tags.set(form.cleaned_data['tags'])
        return redirect('blog:post_detail', post.id)

    return render(
        request=request,
        template_name='blog/create_post.html',
        context={
            'is_edit': True,
            'post': post,
            'form': form,
        }
    )


@login_required
def post_delete(request, post_id, referer):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(referer, post.id)

    redirect_url = referer
    referer = urlparse(referer).path

    post_url = reverse('blog:post_detail', args=[post_id]) + 'edit/'

    if referer == post_url or referer == 'None':
        redirect_url = reverse('blog:index')

    post.delete()
    return redirect(redirect_url, post.id)

journal/templates/blog/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% if is_edit %}
    Редактировать пост {{ post.text|striptags|truncatewords:10 }}
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">

    <h2>{% if is_edit %}Редактирование поста{% else %}Новый пост{% endif %}</h2>

    <form method="post" action="{% if is_edit %}{% url 'blog:post_edit' post.id %}{% else %}{% url 'blog:post_create' %}{% endif %}" enctype="multipart/form-data">
      {% csrf_token %}

      <label title="{{ form.text.help_text }}" for="{{ form.text.id_for_label }}">
        {{form.text.label}}
      </label>
      <div class="form-group row my-2 ">
        {{ form.media }}
        {{ form.text }}
      </div>

      <hr>

      <label title="{{ form.tags.help_text }}" for="{{ form.tags.id_for_label }}">
        {{form.tags.label}}
      </label>
      <div class="form-group row my-2 p-3 bg-white card">
        {{ form.tags }}
      </div>

      <div class="form-group row d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">
          {% if is_edit %}Редактировать пост{% else %}Сохранить пост{% endif %}
        </button>
      </div>

    </form>

  </div>
  <script src="{% static 'js/ckeditor/minWindth.js' %}"></script>
{% endblock %}

journal/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}
{% block content %}
  {% include 'blog/includes/tag/list_all_tags.html' %}
  {% for post in posts_paginator %}
    {% include 'blog/includes/content/content.html' %}
  {% endfor %}
  {% include 'blog/includes/paginator/paginator.html' %}
{% endblock %}

journal/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|striptags|truncatewords:10 }}{% endblock %}
{% block content %}
  <div class="post-container bg-white card">
    {% include 'blog/includes/content/include/post_header.html' %}
    {% include 'blog/includes/content/include/post_body_full.html' %}

    <div class="row">
      {% include 'blog/includes/tag/show_tags_in_post.html' %}
      <div class="col-12 col-md-3">
        <div class="d-flex justify-content-end">

        <!-- эта кнопка видна только автору -->
          {% if post.author == user %}
            <div class="d-flex justify-content-end">
              <a class="btn btn-danger mx-3" href="{% url 'blog:post_delete' post_id=post.id referer=referer %}">
                Удалить
              </a>
              <a class="btn btn-primary" href="{% url 'blog:post_edit' post.id %}">
                Редактировать
              </a>
            </div>
          {% endif %}

          <br>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

journal/templates/blog/profile.html
{% extends 'base.html' %}
{% block title %}Профиль пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="row">
    <div class="col-12 col-md-9">
      <h2>Все посты пользователя: {{ author.get_full_name }} </h2>
    </div>
    <div class="col-12 col-md-3">
      <div class="d-flex justify-content-end">
        <h4>Всего постов: {{ count_posts }} </h4>
      </div>
    </div>
  </div>
  {% include 'blog/includes/tag/list_all_tags.html' %}
  {% for post in posts_paginator %}
    {% include 'blog/includes/content/content.html' %}
  {% endfor %}
  {% include 'blog/includes/paginator/paginator.html' %}
{% endblock %}